# Generated by Django 6.0.3 on 2026-03-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DockerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exit_code", models.IntegerField(null=True)),
                ("stdout", models.TextField(blank=True, null=True)),
                ("stderr", models.TextField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(help_text="运行耗时(秒)", null=True),
                ),
                ("status", models.CharField(default="success", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docker_report",
                        to="core.submission",
                    ),
                ),
            ],
        ),
    ]
