# Generated by Django 6.0.3 on 2026-03-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dockerreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_response", models.TextField(help_text="AI 返回的原始 JSON")),
                ("scores", models.JSONField(help_text="拆分后的维度得分")),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feedback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_evaluation",
                        to="core.submission",
                    ),
                ),
            ],
        ),
    ]
