# Generated by Django 6.0.3 on 2026-03-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aievaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="category",
            field=models.CharField(default="basic", max_length=50),
        ),
        migrations.AddField(
            model_name="assignment",
            name="reference_logic",
            field=models.JSONField(
                default=list, help_text="存储 Layer 3 动态检索的逻辑要点"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="RubricVersion",
        ),
    ]
