# Generated by Django 6.0.3 on 2026-03-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_assignment_category_assignment_reference_logic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="sub_type",
            field=models.CharField(
                choices=[("file", "单文件"), ("archive", "项目压缩包")],
                default="file",
                max_length=10,
            ),
        ),
    ]
