# Generated by Django 6.0.3 on 2026-03-10 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_submission_sub_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgepoint",
            options={"verbose_name": "知识点", "verbose_name_plural": "知识点库"},
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="选课学生",
            ),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="feedback",
            field=models.TextField(verbose_name="导师评语"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="AI 总分"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="category",
            field=models.CharField(
                default="basic", max_length=50, verbose_name="题目难度分类"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="content",
            field=models.TextField(verbose_name="作业要求"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
                verbose_name="所属课程",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="deadline",
            field=models.DateTimeField(verbose_name="截止日期"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="reference_logic",
            field=models.JSONField(
                default=list,
                help_text="存储 Layer 3 动态检索的逻辑要点",
                verbose_name="核心逻辑考点",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="rubric_config",
            field=models.JSONField(
                help_text="存储各维度的评分标准", verbose_name="评分维度配置"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布教师",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=200, verbose_name="作业标题"),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="课程描述"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, verbose_name="课程名称"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授课教师",
            ),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="execution_time",
            field=models.FloatField(
                help_text="运行耗时(秒)", null=True, verbose_name="耗时"
            ),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="exit_code",
            field=models.IntegerField(null=True, verbose_name="退出状态码"),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="stderr",
            field=models.TextField(blank=True, null=True, verbose_name="错误输出"),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="stdout",
            field=models.TextField(blank=True, null=True, verbose_name="标准输出"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="category",
            field=models.CharField(
                max_length=50, null=True, verbose_name="分类(L1/L2)"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
                verbose_name="所属课程",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="是否为系统级(L1)"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="language",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="编程语言"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="name",
            field=models.CharField(max_length=100, verbose_name="知识点名称"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.assignment",
                verbose_name="所属作业",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                upload_to="submissions/%Y/%m/%d/", verbose_name="源文件"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="final_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="最终得分",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="sub_type",
            field=models.CharField(
                choices=[("file", "单文件"), ("archive", "项目压缩包")],
                default="file",
                max_length=10,
                verbose_name="提交类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="class_name",
            field=models.CharField(
                blank=True,
                db_column="class",
                max_length=30,
                null=True,
                verbose_name="班级",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "管理员"), ("teacher", "教师"), ("student", "学生")],
                default="student",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_id_num",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="学号/工号"
            ),
        ),
    ]
