# Generated by Django 6.0.3 on 2026-03-11 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_knowledgepoint_options_course_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评分时间"),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="报告生成时间"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
        ),
    ]
