# Generated by Django 6.0.3 on 2026-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_assignment_created_at_assignment_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aievaluation",
            name="ai_raw_feedback",
            field=models.TextField(null=True, verbose_name="AI 原始评语"),
        ),
        migrations.AddField(
            model_name="aievaluation",
            name="ai_raw_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="AI 建议总分"
            ),
        ),
        migrations.AddField(
            model_name="aievaluation",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="是否向学生公布"),
        ),
        migrations.AddField(
            model_name="aievaluation",
            name="teacher_reviewed",
            field=models.BooleanField(default=False, verbose_name="教师是否已审核"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="max_attempts",
            field=models.IntegerField(default=3, verbose_name="最大允许提交次数"),
        ),
        migrations.AddField(
            model_name="submission",
            name="attempt_number",
            field=models.IntegerField(default=1, verbose_name="尝试次数"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="feedback",
            field=models.TextField(verbose_name="最终评语"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="raw_response",
            field=models.TextField(
                blank=True, help_text="AI 返回的完整原始文本", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="scores",
            field=models.JSONField(help_text="维度得分(JSON)", verbose_name="维度得分"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="最终总分"
            ),
        ),
    ]
