# Generated by Django 6.0.3 on 2026-03-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_aievaluation_ai_raw_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="knowledge_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="assignments",
                to="core.knowledgepoint",
                verbose_name="考查知识点(L1/L2)",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="详细考核逻辑"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="ai_raw_feedback",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="ai_raw_score",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="feedback",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="raw_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="scores",
            field=models.JSONField(verbose_name="维度得分"),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="teacher_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aievaluation",
            name="total_score",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="category",
            field=models.CharField(
                default="basic", max_length=50, verbose_name="难度分类"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="reference_logic",
            field=models.JSONField(
                default=list,
                help_text="Layer 3 动态逻辑点",
                verbose_name="核心逻辑考点",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="execution_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="exit_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="stderr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dockerreport",
            name="stdout",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="name",
            field=models.CharField(
                help_text="如：封装规范、异常处理",
                max_length=100,
                verbose_name="知识点简称",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.assignment"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(upload_to="submissions/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="final_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="sub_type",
            field=models.CharField(
                choices=[("file", "单文件"), ("archive", "项目压缩包")],
                default="file",
                max_length=10,
            ),
        ),
    ]
