# Generated by Django 6.0.3 on 2026-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_assignment_knowledge_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aievaluation",
            name="kp_scores",
            field=models.JSONField(default=dict, verbose_name="知识点细分得分"),
        ),
        migrations.AddField(
            model_name="aievaluation",
            name="raw_sandbox_output",
            field=models.TextField(blank=True, null=True, verbose_name="沙箱原始反馈"),
        ),
        migrations.AddField(
            model_name="dockerreport",
            name="compile_status",
            field=models.BooleanField(default=True, verbose_name="编译状态"),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="name",
            field=models.CharField(max_length=100, verbose_name="知识点简称"),
        ),
    ]
