"""
MOSS Python Client — Based on official Stanford University Protocol
User ID: 791132902 (assigned by Stanford)
Port: 7690 (official)
"""
import socket
import os
import tempfile
import shutil
import difflib


class MOSSChecker:
    """
    Automated Plagiarism Detection Engine.
    Dual-engine strategy:
    1. Stanford MOSS: A remote, high-fidelity structural similarity checker.
    2. Local Diff: A fallback text-based similarity matcher using SequenceMatcher.
    """
    MOSS_HOST = 'moss.stanford.edu'
    MOSS_PORT = 7690  # Official port
    MOSS_USER_ID = '791132902'  # User ID assigned by Stanford

    LANG_MAP = {
        'python': 'python',
        'java': 'java',
    }

    def __init__(self, user_id=None):
        self.user_id = user_id or self.MOSS_USER_ID

    def _send(self, sock, line):
        """
        Helper method to send raw commands to the MOSS socket.
        :param sock: The active socket connection.
        :param line: The command string to send.
        """
        sock.sendall((line + '\n').encode('utf-8'))

    def _check_moss(self, submissions, language):
        """
        Conducts a remote plagiarism check via the Stanford MOSS server.
        Protocol Steps:
        - Handshake and User Authentication.
        - Language and Directory mode configuration.
        - Batch file upload (file id, lang, size, filename).
        - Final query submission to trigger report generation.
        :param submissions: List of (filename, code_content) tuples.
        :param language: The target programming language ('python' or 'java').
        :return: Tuple containing (report_url, parsed_match_list).
        """
        lang = self.LANG_MAP.get(language, 'python')

        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(120)
        sock.connect((self.MOSS_HOST, self.MOSS_PORT))

        try:
            # 1. Authentication
            self._send(sock, f'moss {self.user_id}')

            # 2. Server Configuration
            self._send(sock, 'directory 0')   # 0 = individual files
            self._send(sock, 'X 0')           # 0 = stable production version
            self._send(sock, 'maxmatches 10')
            self._send(sock, 'show 250')

            # 3. Language Negotiation (Server responds with "yes" or "no")
            self._send(sock, f'language {lang}')
            msg = sock.recv(1024).decode('utf-8').strip()
            print(f"[MOSS] Language check: {msg}")
            if msg == 'no':
                self._send(sock, 'end')
                raise ValueError(f"Unsupported language: {lang}")

            # 4. File Stream Upload
            for i, (filename, content) in enumerate(submissions):
                file_content = content if isinstance(content, bytes) else content.encode('utf-8')
                safe_name = filename.replace(' ', '_')
                self._send(sock, f'file {i+1} {lang} {len(file_content)} {safe_name}')
                sock.sendall(file_content)
                print(f"[MOSS] Uploaded: {safe_name} ({len(file_content)} bytes)")

            # 5. Submit Query
            self._send(sock, 'query 0 ')

            # 6. Capture Report URL from server response
            response = sock.recv(4096).decode('utf-8', errors='ignore')
            print(f"[MOSS] Server response: {response}")

            report_url = None
            for line in response.split('\n'):
                if line.strip().startswith('http'):
                    report_url = line.strip()
                    break

            # 7. Finalize connection
            self._send(sock, 'end')

            # 8. Post-processing: Scrape the HTML report for structured data
            parsed = self._parse_moss_report(report_url)

            return report_url, parsed

        finally:
            sock.close()

    def _parse_moss_report(self, report_url):
        """
        Scrapes and parses the MOSS HTML report for match statistics.
        The method uses regex to extract matched file pairs, similarity
        percentages, and builds deep-links for side-by-side comparisons.
        :param report_url: The URL of the report generated by MOSS.
        :return: A list of dicts containing match pairs and similarity metrics.
        """
        import urllib.request
        import re

        import time as _time
        try:
            # Handle MOSS 503 Service Unavailable with a retry loop
            html = None
            for attempt in range(3):
                try:
                    req = urllib.request.Request(report_url, headers={'User-Agent': 'Mozilla/5.0'})
                    with urllib.request.urlopen(req, timeout=30) as resp:
                        html = resp.read().decode('utf-8', errors='ignore')
                    break
                except Exception as e:
                    print(f"[MOSS] Parse attempt {attempt + 1} failed: {e}")
                    if attempt < 2:
                        _time.sleep(3)
            if not html:
                return []

            # 1. Regex to extract match pairs (File paths + Similarity %)
            pair_pattern = r'<a\s+href="([^"]+)">([^<]+?)\s*\((\d+)%\)</a>'
            pairs_raw = re.findall(pair_pattern, html, re.IGNORECASE)

            pairs = []
            for i in range(0, len(pairs_raw), 2):
                if i + 1 < len(pairs_raw):
                    link_a = pairs_raw[i][0]
                    file_a = pairs_raw[i][1].strip()
                    pct_a = int(pairs_raw[i][2])

                    link_b = pairs_raw[i + 1][0]
                    file_b = pairs_raw[i + 1][1].strip()
                    pct_b = int(pairs_raw[i + 1][2])

                    student_a = file_a.split('/')[0] if '/' in file_a else file_a
                    student_b = file_b.split('/')[0] if '/' in file_b else file_b

                    # Build detailed comparison frame URLs
                    detail_urls = self._build_detail_url(report_url, link_a)

                    pairs.append({
                        'file_a': file_a,
                        'file_b': file_b,
                        'student_a': student_a,
                        'student_b': student_b,
                        'similarity': pct_a,
                        'detail_url': detail_urls.get('file_a', ''),
                        'detail_urls': detail_urls
                    })

            # 2. Extract line-by-line evidence for high-risk matches (>70%)
            for pair in pairs:
                if pair['similarity'] > 70 and pair.get('detail_urls'):
                    try:
                        pair['matched_lines'] = self._fetch_detail(pair['detail_urls'])
                    except Exception:
                        pair['matched_lines'] = []

            return pairs

        except Exception as e:
            print(f"[MOSS] Failed to parse report: {e}")
            return []

    def _build_detail_url(self, base_url, link):
        """
        Constructs the URLs for the side-by-side code frames.
        :param base_url: The root URL of the MOSS report.
        :param link: The relative match link (e.g., match0.html).
        :return: Dict containing URLs for the two code frames.
        """
        if link.startswith('http'):
            detail_url = link
        else:
            base = base_url.rsplit('/', 1)[0]
            detail_url = f"{base}/{link}"

        # MOSS generates frames: match0.html -> match0-0.html and match0-1.html
        frame_base = detail_url.replace('.html', '')
        return {
            'file_a': f"{frame_base}-0.html",
            'file_b': f"{frame_base}-1.html"
        }

    def _fetch_detail(self, detail_urls):
        """
        Fetches and identifies highlighted (plagiarized) lines from MOSS frames.
        :param detail_urls: Dict containing frame URLs for side-by-side comparison.
        :return: Dict containing processed lines with 'matched' flags.
        """
        import urllib.request
        import re
        import html as html_mod

        files = []
        for url_key in ['file_a', 'file_b']:
            url = detail_urls.get(url_key)
            if not url:
                files.append({'filename': '', 'lines': []})
                continue
            try:
                req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req, timeout=30) as resp:
                    content = resp.read().decode('utf-8', errors='ignore')

                # 1. Filename extraction
                title_match = re.search(r'<TITLE>(.*?)</TITLE>', content, re.IGNORECASE)
                filename = title_match.group(1) if title_match else url.split('/')[-1]

                # 2. Extract code block inside <PRE>
                pre_match = re.search(r'<PRE>(.*?)</PRE>', content, re.DOTALL | re.IGNORECASE)
                if not pre_match:
                    files.append({'filename': filename, 'lines': []})
                    continue

                pre_raw = pre_match.group(1)

                # 3. Process lines and track <FONT> tags which denote matches
                raw_lines = pre_raw.split('\n')
                processed_lines = []

                in_font = False
                for line in raw_lines:
                    if '<FONT' in line.upper():
                        in_font = True
                    if '</FONT>' in line.upper():
                        in_font = False
                    clean_line = re.sub(r'<[^>]+>', '', line)
                    clean_line = html_mod.unescape(clean_line)
                    processed_lines.append({
                        'code': clean_line,
                        'matched': in_font
                    })

                files.append({'filename': filename, 'lines': processed_lines})

            except Exception as e:
                print(f"[MOSS] Error fetching {url}: {e}")
                files.append({'filename': '', 'lines': []})

        return {
            'files': files,
            'matched_lines': []
        }


    def _check_local(self, submissions):
        """
        Fallback engine for plagiarism detection using local SequenceMatcher.
        :param submissions: List of (filename, code_content) tuples.
        :return: List of matches found using text-based comparison.
        """
        results = []
        for i in range(len(submissions)):
            for j in range(i + 1, len(submissions)):
                name_a, content_a = submissions[i]
                name_b, content_b = submissions[j]
                lines_a = self._normalize(content_a)
                lines_b = self._normalize(content_b)
                matcher = difflib.SequenceMatcher(None, lines_a, lines_b)
                similarity = round(matcher.ratio() * 100, 1)
                if similarity > 30:
                    results.append({
                        'file_a': name_a,
                        'file_b': name_b,
                        'similarity': similarity
                    })
        results.sort(key=lambda x: x['similarity'], reverse=True)
        return results

    def _normalize(self, code):
        """
        Standardizes code to minimize false negatives due to formatting.
        Removes comments and collapses whitespace.
        :param code: Raw source code string.
        :return: List of normalized code lines.
        """
        lines = []
        for line in code.split('\n'):
            stripped = line.strip()
            if not stripped or stripped.startswith('#') or stripped.startswith('//') or stripped.startswith('*'):
                continue
            lines.append(' '.join(stripped.split()))
        return lines

    def check_plagiarism(self, submissions, language='python'):
        """
        High-level entry point for plagiarism checks.
        Attempts MOSS first; uses the Local engine as a safety fallback.
        :param submissions: List of (filename, code_content) tuples.
        :param language: The target programming language.
        :return: Detection report including report URL and matched pairs.
        """
        temp_dir = tempfile.mkdtemp()
        try:
            file_count = 0
            for i, (filename, content) in enumerate(submissions):
                safe_filename = filename.replace('/', '_').replace('\\', '_')
                filepath = os.path.join(temp_dir, f"student_{i}_{safe_filename}")
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content if isinstance(content, str) else content.decode('utf-8', errors='ignore'))
                file_count += 1

            if file_count < 2:
                return {'error': 'Need at least 2 submissions', 'report_url': None, 'mode': None}

            # Phase 1: Attempt Remote MOSS Check
            try:
                report_url, parsed = self._check_moss(submissions, language)
                if report_url:
                    print(f"[MOSS] Success: {report_url}, {len(parsed)} pairs")
                    return {
                        'report_url': report_url,
                        'file_count': file_count,
                        'language': language,
                        'mode': 'moss',
                        'matches': parsed
                    }
            except Exception as e:
                print(f"[MOSS] Failed: {e}")

            # Phase 2: Fallback to Local Detection
            local_results = self._check_local(submissions)
            print(f"[Local] Found {len(local_results)} pairs")
            return {
                'report_url': None,
                'file_count': file_count,
                'language': language,
                'mode': 'local',
                'matches': local_results
            }

        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)