import os
import zipfile
import re
import shutil


class ProjectAnalyzer:
    """
    Multi-file project structure analyzer.

    This class is responsible for extracting the uploaded ZIP archive, normalizing it, and using "heuristic regular matching + AI semantic analysis".
    Is a dual mechanism that automatically identifies the Entry Point of a program in a complex directory tree.

    Attributes:
        ai_client: AI client for decision aid (like AIScorer instance).
    """
    def __init__(self, ai_client=None):
        self.ai_client = ai_client

    def unzip_project(self, zip_path, extract_path):
        """
        Unzip the project archive and recursively perform directory tiling.

        This method automatically handles common "folder nesting" issues (e.g., students packing entire folders when compressing, resulting in
        Redundant top-level directories after unzipping). It will ensure that the core content of the project (such as the src directory or main file)
        Is promoted to the first level of the decompression path.
        :param zip_path: ZIP file's physical path
        :param extract_path: Target unzipped directory.
        :return:
        """
        if not os.path.exists(extract_path):
            os.makedirs(extract_path, exist_ok=True)
        try:
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(extract_path)

            # --- Recursive tiling: Make sure the src directory is on the first level of extract_path ---
            while True:
                content = [f for f in os.listdir(extract_path) if
                           not f.startswith('__MACOSX') and not f.startswith('.')]
                if len(content) == 1 and os.path.isdir(os.path.join(extract_path, content[0])):
                    nested_folder = os.path.join(extract_path, content[0])
                    for item in os.listdir(nested_folder):
                        shutil.move(os.path.join(nested_folder, item), extract_path)
                    os.rmdir(nested_folder)
                else:
                    break
            print(f"Unzip completed: {extract_path}")
        except Exception as e:
            print(f"Unzip failed: {str(e)}")
            raise e

    def heuristic_detect(self, project_path):
        """
        Heuristic Entry Detection with Regular Expressions.

        By scanning the source code for specific flags:
        - Python: Look for the 'if __name__ == "__main__":' struct.
        - Java: Find the 'public static void main(String[] args)' method.
        :param project_path: Project root
        :return: List of all candidate entry file relative paths found.
        """
        candidates = []
        py_entry_patterns = [r'if\s+__name__\s*==\s*["\']__main__["\']\s*:']
        java_main_pattern = r'public\s+static\s+void\s+main\s*\('

        for root, _, files in os.walk(project_path):
            for file in files:
                path = os.path.join(root, file)
                rel_path = os.path.relpath(path, project_path).replace("\\", "/")
                if file.endswith('.py'):
                    try:
                        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                            if any(re.search(p, f.read()) for p in py_entry_patterns):
                                candidates.append(rel_path)
                    except:
                        pass
                elif file.endswith('.java'):
                    try:
                        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                            if re.search(java_main_pattern, f.read()):
                                candidates.append(rel_path)
                    except:
                        pass
        return list(set(candidates))

    def ai_assist_detect(self, project_path, candidates, task_context=None):
        """
        AI is used to assist the "authenticity" discrimination of entry points.

        When a project has multiple entries (e.g., multiple test classes with main methods),
        This method sends the code snippet of each candidate file to the AI, combined with the task_context.
        Decide which one is the real entry point to the business logic.
        :param project_path: Project path.
        :param candidates: The list of candidates detected by the heuristic
        :param task_context: The description of the task or the background of the test point to help the AI improve the accuracy of the judgment.
        :return: Optimal entry file path determined by AI.
        """
        if not self.ai_client:
            return candidates[0] if candidates else None

        # It is preferred to exclude Main.java because it is usually an empty file generated by the IDE
        filtered_candidates = [c for c in candidates if "Main.java" not in c]
        if not filtered_candidates: filtered_candidates = candidates

        candidate_snippets = ""
        for path in filtered_candidates[:5]:
            try:
                full_path = os.path.join(project_path, path)
                with open(full_path, 'r', encoding='utf-8', errors='ignore') as f:
                    snippet = "".join(f.readlines()[:30])
                    candidate_snippets += f"\n--- FILE: {path} ---\n{snippet}\n"
            except:
                continue

        prompt = f"""
        You are a Software Architect. Identify the "Real Business Logic Entry Point" from these candidates.
        [Context]: {task_context}
        [Files]: {candidate_snippets}
        [Constraint]: Return ONLY the raw file path string.
        """
        response = self.ai_client.ask(prompt).strip()
        return response.replace('`', '').split('\n')[0].strip()

    def get_entry_point(self, project_path, task_context=None):
        """
        The main entrance of the integrated identification project.

        A complete pipeline for integrating heuristic scanning with AI arbitration. This is the core method called by the Pipeline.
        :return: The final entry path, returning None if not found.
        """
        candidates = self.heuristic_detect(project_path)
        if not candidates: return None
        # If there are multiple entries, ask the AI to arbitrate instead of simply returning
        return self.ai_assist_detect(project_path, candidates, task_context)