import os
import shutil
import json
import re
from celery import shared_task
from django.utils import timezone
from datetime import timedelta
from django.db.models import Max, Avg
from django.db import transaction
from django.core.mail import send_mail

from Backend import settings
from .models import Assignment, Submission, User, TeachingInsightReport
from .utils.grading_pipeline import GradingPipeline
from .utils.ai_scorer import AIScorer

@shared_task
def run_grading_task(submission_id, temp_workspace, entry_point=None):
    """
    Celery asynchronous scoring task.

    Responsibilities:
    1. Task scheduling: instantiate GradingPipeline and trigger the full grading process.
    2. Resource isolation: Runs in a separate Celery Worker process without blocking Web services.
    3. Environment cleanup: Whether scoring succeeds or fails, forcibly delete the temporary workspace generated by unpacking the source code to prevent disk overflow.

    Args:
    submission_id (int): The ID of the commit record to be corrected.
    temp_workspace (str): Path to a temporary directory to store the student source code.
    entry_point (str, optional): Analytically determined relative path to the project's main entry file.
    """
    print(f"--- Celery receives the assignment: Submission {submission_id} ---")

    try:
        pipeline = GradingPipeline(submission_id)

        # 🚀 核心修复：无论 entry_point 是否有值，都必须传入 work_dir (即 temp_workspace)
        # 这样当 entry_point 为 None 时，Pipeline 内部的搜索逻辑才能在 temp_workspace 里找到代码文件
        pipeline.run_full_pipeline(entry_point=entry_point, work_dir=temp_workspace)

    except Exception as e:
        print(f"🚨 Celery Task Error: {str(e)}")
    finally:
        # 无论成功失败，清理临时目录
        if temp_workspace and os.path.exists(temp_workspace):
            shutil.rmtree(temp_workspace, ignore_errors=True)
            print(f" Temporary directory cleared: {temp_workspace}")


# ---------------------------------------------------------
# 任务 2: 全局动态通知调度器 (由 Celery Beat 每分钟触发)
# ---------------------------------------------------------
@shared_task
def check_deadlines_and_send_reports():
    """
    Orchestrator Task: Scans for assignments reaching their reporting threshold
    based on individual teacher preferences.

    Workflow:
    1. Filter: Targets only teachers who have explicitly opted into reports.
    2. Window Calculation: Determines the 'Trigger Zone' by adding the teacher's
       custom offset to the current time.
    3. Selection: Identifies assignments that have entered this zone but haven't
       been processed yet (report_sent=False).
    4. Delegation: Offloads the intensive report generation to an asynchronous worker.
    """
    now = timezone.now()

    # 1. Get only the configuration that has global reporting notifications enabled
    from .models import NotificationConfig, Assignment
    configs = NotificationConfig.objects.filter(enable_report=True).select_related('teacher')

    for config in configs:
        # 2. Calculate the trigger time window for this teacher
        trigger_limit = now + timedelta(hours=config.remind_before_hours)

        # 3. Find assignments under the teacher's name that have reached their trigger time and have not yet sent a report
        pending_assignments = Assignment.objects.filter(
            teacher=config.teacher,
            report_sent=False,
            deadline__lte=trigger_limit
        )

        for assignment in pending_assignments:

            # 4. The send task is called asynchronously, passing in the title template defined by the teacher
            send_assignment_deadline_report.delay(
                assignment.id,
                subject_template=config.subject_template
            )


# ---------------------------------------------------------
# 任务 3: 生成并发送详细成绩报告邮件 (配置适配版)
# ---------------------------------------------------------
@shared_task(bind=True, max_retries=3)
def send_assignment_deadline_report(self, assignment_id, subject_template=None):
    """
    Asynchronous task to send a statistical report email to the teacher after an assignment deadline.

    Workflow:
    1. Aggregates submission stats (total count, submission rate, and average score).
    2. Identifies students who have not submitted.
    3. Generates a snapshot of scores based on each student's highest attempt.
    4. Marks the report as sent in the database.
    :param self: Task instance for retries.
    :param assignment_id: ID of the Assignment to report on.
    :param subject_template: Optional string for custom email subjects (supports {title}).
    :return:
    """
    try:
        # Preload related data to optimize performance and prevent N+1 queries
        from .models import Assignment, Submission
        assignment = Assignment.objects.select_related('teacher', 'course').get(id=assignment_id)
        teacher = assignment.teacher

        if not teacher.email:
            print(f"Skip: Teacher {teacher.username} has no email set.")
            return

        # 1. Basic data statistics
        all_students = assignment.course.students.all()
        total_count = all_students.count()

        # Get the QuerySet of all completed commits
        submitted_qs = Submission.objects.filter(assignment=assignment, status='completed')
        submitted_count = submitted_qs.values('student').distinct().count()

        # 2. Calculate the average score (take the highest score of each student and average it)
        avg_score = submitted_qs.values('student').annotate(
            best=Max('final_score')
        ).aggregate(average=Avg('best'))['average'] or 0

        # 3. Student list not submitted
        unsubmitted_students = all_students.exclude(
            id__in=Submission.objects.filter(
                assignment=assignment, status='completed'
            ).values_list('student_id', flat=True)
        )
        unsubmitted_list = [f"- {s.first_name or s.username} (ID: {s.student_id_num or 'N/A'})" for s in
                            unsubmitted_students]

        # 4. Batch Score Retrieval (Performance Optimization)
        best_scores = {}
        for row in submitted_qs.values('student').annotate(best=Max('final_score')):
            best_scores[row['student']] = row['best']

        score_details = []
        for student in all_students:
            score = best_scores.get(student.id)
            score_str = f"{score} pts" if score is not None else "Not Submitted"
            score_details.append(
                f"{student.first_name or student.username} ({student.student_id_num or 'N/A'}): {score_str}"
            )

        # 5. Build Email Content
        if subject_template:
            subject = subject_template.format(title=assignment.title)
        else:
            subject = f"[System Notification] Assignment Deadline Report:《{assignment.title}》"

        unsubmitted_text = "\n".join(unsubmitted_list) if unsubmitted_list else "Congratulations! All students submitted on time."
        score_details_text = "\n".join(score_details)

        message = f"""
Dear Professor {teacher.first_name or teacher.username}:

The statistical report for the assignment "{assignment.title}" in course "{assignment.course.name}" is now ready.

[Overview]
-----------------------------------
- Deadline: {assignment.deadline.strftime('%Y-%m-%d %H:%M')}
- Total Students: {total_count}
- Submissions: {submitted_count}
- Submission Rate: {(submitted_count / total_count * 100) if total_count > 0 else 0:.1f}%
- Class Average (Based on best scores): {avg_score:.2f}

[Missing Submissions ({total_count - submitted_count} students)]
-----------------------------------
{unsubmitted_text}

[Detailed Score Snapshot]
-----------------------------------
{score_details_text}

Please log in to the "Grading Workspace" to review the source code.

---
This email was automatically generated based on system configurations.
Generated at: {timezone.now().strftime('%Y-%m-%d %H:%M:%S')}
        """

        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [teacher.email],
            fail_silently=False,
        )

        print(f"Report successfully sent: {assignment.title} -> {teacher.email}")
        Assignment.objects.filter(id=assignment_id).update(report_sent=True)

    except Assignment.DoesNotExist:
        print(f"Error: Assignment ID {assignment_id} not found.")
    except Exception as e:
        print(f"Failed to send email: {str(e)}. Retrying...")
        raise self.retry(exc=e, countdown=60)


@shared_task(
    bind=True,
    max_retries=2,
    name='analyze_task'
)
def async_generate_teaching_insights(self, assignment_id):
    """
    异步教情诊断任务：
    1. 聚合班级最高分数据
    2. 计算知识点掌握度汇总
    3. 调用 AI 教授模型进行深度诊断
    4. 将结果持久化到 TeachingInsightReport 表
    """
    print("\n" + "=" * 30)
    print(f"🔥 WORKER IS ACTUALLY RUNNING: {assignment_id}")
    print("=" * 30 + "\n")
    report = None
    try:
        # --- 初始化：获取对象并标记状态 ---
        print(f"🚀 [TASK START] Processing Assignment ID: {assignment_id}")
        assignment = Assignment.objects.get(id=assignment_id)

        # 获取或创建报告记录
        report, _ = TeachingInsightReport.objects.get_or_create(assignment=assignment)
        report.status = 'pending'
        report.save()

        # --- 1. 数据聚合逻辑 (基于内存去重，确保统计的是每位学生的最优表现) ---
        all_subs = Submission.objects.filter(
            assignment=assignment,
            status='completed'
        ).order_by('student', '-final_score', '-id').select_related('student', 'ai_evaluation')

        best_submissions = []
        seen_students = set()
        for s in all_subs:
            if s.student_id not in seen_students:
                if hasattr(s, 'ai_evaluation'):
                    best_submissions.append(s)
                    seen_students.add(s.student_id)

        if not best_submissions:
            print(f"⚠️ [TASK] No submissions found for assignment {assignment_id}")
            report.status = 'error'
            report.save()
            return "No submissions found"

        # --- 2. 统计指标计算 ---
        kp_stats = {}
        common_issues = []
        total_score_sum = 0

        for sub in best_submissions:
            total_score_sum += float(sub.final_score or 0)
            evaluation = sub.ai_evaluation

            # 聚合知识点得分
            if evaluation.kp_scores and isinstance(evaluation.kp_scores, dict):
                for kp_name, score in evaluation.kp_scores.items():
                    if kp_name not in kp_stats:
                        kp_stats[kp_name] = []
                    kp_stats[kp_name].append(float(score))

            # 收集反馈片段用于 AI 上下文
            if evaluation.feedback:
                common_issues.append(evaluation.feedback[:300])

        # 格式化知识点汇总
        kp_summary_text = []
        for name, v in kp_stats.items():
            avg_v = round(sum(v) / len(v), 1)
            min_v = round(min(v), 1)
            max_v = round(max(v), 1)
            weak_n = sum(1 for s in v if s < 60)
            kp_summary_text.append(
                f"- {name}: avg={avg_v}, min={min_v}, max={max_v}, weak_students={weak_n}/{len(v)}"
            )
        class_avg = round(total_score_sum / len(best_submissions), 1)

        # --- 3. 🤖 调用 AI (灵魂 Prompt) ---
        scorer = AIScorer()
        prompt = f"""
        You are a senior Computer Science Professor. Analyze the class performance for the assignment: '{assignment.title}'.

        [Statistical Data]
        - Total Students (Best Attempts): {len(best_submissions)}
        - Class Average: {class_avg}
        - Knowledge Point Mastery: 
        {chr(10).join(kp_summary_text)}

        [Student Feedback Snippets]
        {chr(10).join(common_issues[:10])}

        [Task]
        Based on the data, identify collective weaknesses and provide actionable teaching advice.
        For each weakness found, reference the specific knowledge point name and the number of students affected.

        [Output Requirement]
        Return ONLY a JSON object with:
        - "analysis": A brief summary of class performance (2-3 sentences, in English).
        - "strengths": A list of 2 key areas where the class excelled, citing specific KP names.
        - "weaknesses": A list of 2 key areas needing improvement, citing specific KP names and weak student counts.
        - "suggestions": A list of 3 specific, actionable teaching adjustments for the next lecture (in English).
        """

        print("🤖 [TASK] Calling AI Scorer...")
        raw_res = scorer.ask(prompt)
        print("✅ [TASK] AI Scorer Responded!")

        # --- 4. 健壮的 JSON 解析逻辑 ---
        try:
            # 这里的正则比 re.sub 更强，它会抓取第一个 { 和最后一个 } 之间的内容
            json_match = re.search(r'\{.*\}', raw_res, re.DOTALL)
            if json_match:
                clean_json_str = json_match.group()
            else:
                clean_json_str = raw_res

            insights = json.loads(clean_json_str)
        except Exception as json_err:
            print(f"❌ [TASK] JSON Parse Error: {str(json_err)}")
            # 即使解析失败，也手动构造一个结构，防止状态卡在 pending
            insights = {
                "analysis": "AI response format error — please review raw data below.",
                "strengths": ["Data parsing failed"],
                "weaknesses": ["Data parsing failed"],
                "suggestions": ["Please click 'Analyze' again to retry."],
                "raw_data": raw_res[:200]  # 记录前200个字备查
            }

        # --- 5. 数据持久化回填 ---
        report.stats_data = {
            "count": len(best_submissions),
            "average": class_avg,
            "kp_mastery": {k: round(sum(v) / len(v), 1) for k, v in kp_stats.items()}
        }
        report.ai_insights = insights
        report.status = 'ready'  # 🚀 关键：标记为 ready 才会停止轮询
        report.save()

        print(f"🎉 [TASK SUCCESS] Report updated for {assignment.title}")
        return f"Success for {assignment.id}"

    except Exception as e:
        print(f"🔥 [TASK FATAL ERROR] {str(e)}")
        if report:
            report.status = 'error'
            report.save()
        # 异常重试逻辑
        raise self.retry(exc=e, countdown=60)

def _aggregate_by_student(raw_matches):
    """将文件级对比聚合为学生级分析"""
    from collections import defaultdict

    # 1. 按学生对聚合
    student_pairs = defaultdict(lambda: {'similarity_sum': 0, 'count': 0, 'max_similarity': 0, 'files': []})

    for m in raw_matches:
        a = m.get('student_a', m.get('file_a', '').split('/')[0])
        b = m.get('student_b', m.get('file_b', '').split('/')[0])
        sim = m.get('similarity', 0)

        key = tuple(sorted([a, b]))

        student_pairs[key]['similarity_sum'] += sim
        student_pairs[key]['count'] += 1
        student_pairs[key]['max_similarity'] = max(student_pairs[key]['max_similarity'], sim)

        student_pairs[key]['files'].append({
            'file_a': m.get('file_a', ''),
            'file_b': m.get('file_b', ''),
            'similarity': sim,
            'detail_urls': m.get('detail_urls', {})
        })

    # 2. 计算每个学生对的平均相似度
    aggregated = []
    for (a, b), data in student_pairs.items():
        avg_sim = round(data['similarity_sum'] / data['count'], 1) if data['count'] > 0 else 0
        aggregated.append({
            'student_a': a,
            'student_b': b,
            'avg_similarity': avg_sim,
            'max_similarity': data['max_similarity'],
            'matched_files': data['count'],
            'files': sorted(data['files'], key=lambda x: x['similarity'], reverse=True)[:10]
        })

    aggregated.sort(key=lambda x: x['max_similarity'], reverse=True)

    # 3. 生成学生风险排名
    student_risk = defaultdict(lambda: {'high': 0, 'medium': 0, 'low': 0, 'total_pairs': 0})
    for pair in aggregated:
        for s in [pair['student_a'], pair['student_b']]:
            student_risk[s]['total_pairs'] += 1
            if pair['max_similarity'] > 80:
                student_risk[s]['high'] += 1
            elif pair['max_similarity'] > 50:
                student_risk[s]['medium'] += 1
            else:
                student_risk[s]['low'] += 1

    risk_summary = []
    for student, risk in student_risk.items():
        risk_level = 'high' if risk['high'] > 0 else ('medium' if risk['medium'] > 0 else 'low')
        risk_summary.append({
            'student': student,
            'risk_level': risk_level,
            'high_count': risk['high'],
            'medium_count': risk['medium'],
            'total_pairs': risk['total_pairs']
        })
    risk_summary.sort(key=lambda x: (0 if x['risk_level'] == 'high' else 1 if x['risk_level'] == 'medium' else 2))

    return {
        'student_pairs': aggregated,
        'risk_summary': risk_summary,
        'total_pairs': len(aggregated),
        'high_risk_count': sum(1 for p in aggregated if p['max_similarity'] > 80),
        'medium_risk_count': sum(1 for p in aggregated if 50 < p['max_similarity'] <= 80)
    }


@shared_task(bind=True, max_retries=2)
def async_plagiarism_check(self, report_id, assignment_id):
    """异步代码查重任务"""
    from .models import PlagiarismReport, Submission
    from .utils.moss_checker import MOSSChecker

    report = PlagiarismReport.objects.get(id=report_id)
    try:
        assignment = Assignment.objects.get(id=assignment_id)

        # 收集每个学生的最优提交
        submissions = Submission.objects.filter(
            assignment=assignment, status='completed'
        ).order_by('student', '-final_score', '-id').select_related('student')

        import zipfile
        best_subs = []
        seen_students = set()

        for sub in submissions:
            if sub.student_id not in seen_students:
                seen_students.add(sub.student_id)
                if not sub.file or not os.path.exists(sub.file.path):
                    continue

                file_path = sub.file.path
                filename = os.path.basename(file_path)

                # ZIP 文件：解压提取源码
                if filename.lower().endswith('.zip'):
                    try:
                        with zipfile.ZipFile(file_path, 'r') as zf:
                            for info in zf.infolist():
                                if info.filename.lower().endswith(('.py', '.java')) and not info.is_dir():
                                    code = zf.read(info.filename).decode('utf-8', errors='ignore')
                                    safe_name = f"{sub.student.username}/{info.filename}"
                                    best_subs.append((safe_name, code))
                    except Exception:
                        continue
                # 单个源码文件：直接读取
                elif filename.lower().endswith(('.py', '.java')):
                    try:
                        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                            best_subs.append((f"{sub.student.username}/{filename}", f.read()))
                    except Exception:
                        continue

        if len(best_subs) < 2:
            report.status = 'error'
            report.error_message = 'Need at least 2 submissions with files'
            report.save()
            return

        # 执行查重
        checker = MOSSChecker()
        result = checker.check_plagiarism(best_subs, language=assignment.category)

        # 持久化结果
        report.mode = result.get('mode')
        report.report_url = result.get('report_url')
        raw_matches = result.get('matches', [])
        report.file_count = result.get('file_count', 0)

        # 学生级别聚合分析
        report.matches = _aggregate_by_student(raw_matches)
        report.status = 'completed'
        report.save()

    except Exception as e:
        report.status = 'error'
        report.error_message = str(e)
        report.save()
        raise self.retry(exc=e, countdown=60)


@shared_task
def async_appeal_audit(appeal_id):
    from .models import Appeal
    from .utils.appeal_service import AppealService
    appeal = Appeal.objects.get(id=appeal_id)
    sub = appeal.evaluation.submission
    result = AppealService.process_student_appeal(sub, appeal.student_reason)
    appeal.ai_judgment = result.get('ai_judgment', 'AI audit completed.')
    appeal.status = 'pending_teacher' if result.get('is_reasonable', False) else 'rejected_by_ai'
    appeal.save()
