from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    MyTokenObtainPairView,
    TeacherAssignmentViewSet,
    TeacherCourseViewSet,
    TeacherStudentManagementViewSet,
    StudentAssignmentViewSet,
    StudentSubmissionViewSet,
    StudentCourseViewSet,
    UserProfileViewSet,
    get_global_assignment_reminders
)
from rest_framework_simplejwt.views import TokenRefreshView

# Initialize the DRF default router
router = DefaultRouter()

# --- Teacher side interface ---
# /api/auth/teacher/assignments/
router.register(r'teacher/assignments', TeacherAssignmentViewSet, basename='teacher-assignment')
# /api/auth/teacher/courses/
router.register(r'teacher/courses', TeacherCourseViewSet, basename='teacher-course')
# /api/auth/teacher/students/
router.register(r'teacher/students', TeacherStudentManagementViewSet, basename='teacher-student')

# --- Student side interface ---
# /api/auth/student/assignments/
router.register(r'student/assignments', StudentAssignmentViewSet, basename='student-assignment')
# /api/auth/student/submissions/
router.register(r'student/submissions', StudentSubmissionViewSet, basename='student-submission')
# /api/auth/student/courses/  <-- 新增这个
router.register(r'student/courses', StudentCourseViewSet, basename='student-course')

# --- General function module ---
# User profile modification, password change, etc
router.register(r'profile', UserProfileViewSet, basename='user-profile')

# define the final list of URL mappings
urlpatterns = [
    # 1. Automated API path generated by the router
    path('', include(router.urls)),

    # 2. Authentication path
    path('login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # 3. Global service notification
    path('home/reminders/', get_global_assignment_reminders, name='home-reminders'),
]
