import os
import uuid
import shutil
import pandas as pd
import traceback
from django.conf import settings
from django.db import transaction
from django.contrib.auth.hashers import make_password
from rest_framework import viewsets, permissions, status, serializers
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework.decorators import action

# Import the model and serializer
from .models import User, Course, Assignment, Submission, AIEvaluation, KnowledgePoint
from .serializers import (
    AssignmentSerializer,
    SubmissionSerializer,
    MyTokenObtainPairSerializer,
    CourseSerializer
)
from .utils.ai_scorer import AIScorer
from .utils.project_analyzer import ProjectAnalyzer


# Identity verification and permissions

class MyTokenObtainPairView(TokenObtainPairView):
    """
    Customize the JWT login view.
    By associating a custom serializer
    After the success of the MyTokenObtainPairSerializer, realize the user login
    Return additional user information (like role, username, etc.) instead of just access and refresh tokens.
    Attributes:
        serializer_class (Serializer): This points to a custom token grabber serializer.
    """
    serializer_class = MyTokenObtainPairSerializer


class IsTeacher(permissions.BasePermission):
    """
    Custom permission validation class: Teacher role only access.
    This class is used in the permission_classes configuration of DRF views
    to implement fine-grained interface access control by checking the authentication status and role fields of the requesting user.
    """

    def has_permission(self, request, view):
        """
        Determines whether the current requested user has access permissions.
        :param request: DRF request object, which contains user information.
        :param view: The view instance currently attempting to access.
        :return: bool: Returns True if the user is logged in and the role is 'teacher', False otherwise.
        """
        return request.user.is_authenticated and request.user.role == 'teacher'


# Teacher Side View

class TeacherAssignmentViewSet(viewsets.ModelViewSet):
    """
    Teacher-side assessment management view set.
    Provides standard CRUD functionality for assignments,
    The core business logic such as knowledge point association, score batch release and manual grading is integrated.

    Permission Restrictions:
    Access is restricted to authenticated users with the 'teacher' role.
    """
    queryset = Assignment.objects.all().order_by('-id')
    serializer_class = AssignmentSerializer
    permission_classes = [IsTeacher]

    # 这里需要稍作修改，作业与知识点的关系
    def perform_create(self, serializer):
        """
        Save the newly created assignment instance, and associate the teacher and the knowledge point.
        This method overrides the parent class's perform_create to ensure that the currently logged in teacher is automatically logged in when the job is created
        Set as the owner of the job and handle many-to-many relationships (KnowledgePoints) manually.
        :param serializer: Validated job serializer instance
        :return: none
        """
        kp_ids = self.request.data.get('knowledge_points', [])
        assignment = serializer.save(teacher=self.request.user)
        if kp_ids:
            assignment.knowledge_points.set(kp_ids)

    @action(detail=True, methods=['post'], url_path='publish-all')
    def publish_all_results(self, request, pk=None):
        """
        Batch release of all AI scoring results for a given assessment.
        This interface will attach the AIEvaluation of all Submissions associated with the assessment.
        The 'is_published' status of is consistently updated to True, allowing students to view the results.
        :param request: DRF request object
        :param pk: The unique identification ID of the assessment, which is automatically captured by the URL path.
        :return: Response: A JSON response containing the number of records that were successfully updated
        """
        assignment = self.get_object()
        evals = AIEvaluation.objects.filter(submission__assignment=assignment)
        count = evals.update(is_published=True)
        return Response({"message": f"Successfully published {count} records"})

    @action(detail=False, methods=['post'], url_path='update-score')
    def update_score(self, request):
        """
        Manually update and publish student grades (manually reviewed by teachers)
        The interface allows the teacher to override the grading results and feedback automatically generated by the AI.
        While updating the evaluation record,
        The final score for the associated Submission is updated synchronously and automatically set to published status.
        :param request: A DRF request object containing the following data:
            submission_id (int): The associated commit record ID.
            score (Decimal/float): The new score given by the instructor
            feedback (str): Comments or revised feedback given by the teacher.
        :return: Response: Success message or 404 error (if the rating doesn't exist)
        """
        submission_id = request.data.get('submission_id')
        new_score = request.data.get('score')
        new_feedback = request.data.get('feedback')
        try:
            evaluation = AIEvaluation.objects.get(submission_id=submission_id)
            evaluation.total_score = new_score
            evaluation.feedback = new_feedback
            evaluation.teacher_reviewed = True
            evaluation.is_published = True
            evaluation.save()
            sub = evaluation.submission
            sub.final_score = new_score
            sub.save()
            return Response({"message": "The results have been updated and published"})
        except AIEvaluation.DoesNotExist:
            return Response({"error": "Evaluation records do not exist"}, status=404)


class TeacherCourseViewSet(viewsets.ModelViewSet):
    """
    Set of views for teacher-side course management.
    Provides full CRUD functionality for courses. The view set fetches logic by rewriting the query set,
    Strict data isolation is implemented to ensure that teachers can only manage the courses under their own names.
    Permission Restrictions: Access is restricted to authenticated users with the 'teacher' role.
    """
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = [IsTeacher]

    def get_queryset(self):
        """
        The query set acquisition logic was rewritten to achieve data isolation.
        Filtering by the user currently requesting (request.user) ensures that the list of courses is returned
        Only courses created or responsible for by the instructor are included.
        :return:
            QuerySet: The set of courses associated with the currently logged-in teacher.
        """
        return Course.objects.filter(teacher=self.request.user)

    def perform_create(self, serializer):
        """
        Automatically associate the current teacher when saving a new course.
        Override the hook function to inject teacher information before the database is saved, preventing the front end from passing through
        Tampering with teacher ids to create courses across permissions.
        :param serializer: Validated course serializer.
        :return:
        """
        # Force the teacher field of the course to be the current logged-in user
        serializer.save(teacher=self.request.user)

    @action(detail=True, methods=['get'], url_path='students')
    def enrolled_students(self, request, pk=None):
        """
        Obtain the list of registered students for the current specific course.
        This interface queries the information of all students who have taken the course by associating with the course ID, and manually extracts the key fields for return.
        It is mainly used for data display on the "Student Management" page of the teacher end.
        :param request: DRF Request Object.
        :param pk: Course unique identifier ID (automatically captured by the URL)
        :return: Response: A list containing information such as student ID, student number, name, and class.
        """
        course = self.get_object()
        students = course.students.all()

        student_data = [{
            "id": s.id,
            "username": s.username,
            "name": s.first_name,
            "student_id_num": s.student_id_num,
            "class_name": s.class_name
        } for s in students]

        return Response(student_data)

    @action(detail=True, methods=['post'], url_path='remove-students')
    def bulk_remove_students(self, request, pk=None):
        """
        Batch remove enrolled students from the current course.
        This operation only breaks the many-to-many association between the Course and the Student (enrollment relationship),
        and will not delete the student accounts in the User table. Teachers can select multiple students on the interface and perform the removal operation at once.
        :param request: A request including the list of student IDs to be removed.
        :param pk: Target course ID
        :return: Response: Success message and the actual number of students removed.
        """
        course = self.get_object()
        student_ids = request.data.get('student_ids', [])

        if not student_ids:
            return Response({"error": "Please select the student to be removed."}, status=400)

        try:
            students_to_remove = course.students.filter(id__in=student_ids)
            count = students_to_remove.count()

            course.students.remove(*students_to_remove)

            return Response({
                "message": f"Successfully removed {count} students from the course.",
                "removed_count": count
            })
        except Exception as e:
            return Response({"error": str(e)}, status=500)


class TeacherStudentManagementViewSet(viewsets.ViewSet):
    """
    Teacher end student management view set.
    It provides administrative management functions for student accounts, such as batch import and account initialization.
    This view set is not directly associated with a single model, but operates as a functional control center.
    Permission restrictions: Access is restricted to authenticated users with the 'teacher' role only.
    """
    permission_classes = [IsTeacher]

    @action(detail=False, methods=['post'], url_path='import-students')
    def import_students(self, request):
        """
        Batch create student accounts by uploading Excel/CSV files, and optionally add them to the specified courses.
        :param request: DRF Request Object.
        :return: Response: A successful statistical message including the number of newly created students and the number of students who have enrolled in the course.
        """
        file = request.FILES.get('file')
        course_id = request.data.get('course_id')

        if not file:
            return Response({"error": "请上传 Excel 或 CSV 文件"}, status=400)

        try:
            df = pd.read_csv(file) if file.name.endswith('.csv') else pd.read_excel(file)
            df.columns = [c.strip().lower() for c in df.columns]

            created_count = 0
            enrolled_count = 0

            with transaction.atomic():
                target_course = None
                if course_id:
                    target_course = Course.objects.get(id=course_id, teacher=request.user)

                for _, row in df.iterrows():
                    sid = str(row.get('student_id', '')).strip()
                    if not sid or sid == 'nan':
                        continue

                    user, created = User.objects.get_or_create(
                        student_id_num=sid,
                        defaults={
                            'username': sid,
                            'first_name': str(row.get('name', '')).strip(),
                            'class_name': str(row.get('class', '')).strip(),
                            'role': 'student',
                            'password': make_password(sid)
                        }
                    )

                    if created:
                        created_count += 1

                    if target_course:
                        if not target_course.students.filter(id=user.id).exists():
                            target_course.students.add(user)
                            enrolled_count += 1

            return Response({
                "message": f"Import successful: {created_count} new students have been created, and {enrolled_count} students have been enrolled in the course."
            })

        except Course.DoesNotExist:
            return Response({"error": "The specified course does not exist or you do not have the authority to operate this course."}, status=404)
        except Exception as e:
            import traceback
            traceback.print_exc()
            return Response({"error": f"Table parsing failed: {str(e)}"}, status=400)


# Student Side View

class StudentAssignmentViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Student side assignments view set
    Provide only read-only operations (List/Retrieve),
    Allowing students to view all assignments for their course,
    It also supports querying the submission and rating status of a specific job through custom actions.
    Permission Restrictions: Access is restricted to logged-in users (student role) only.
    """
    serializer_class = AssignmentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """
        Get a list of assignments for the current student's course.
        Filtering through many-to-many relationships,
        Make sure students can only see assignments posted under their Course, sorted by due date in descending order.
        :return: QuerySet: A filtered list of assessments
        """
        return Assignment.objects.filter(course__students=self.request.user).distinct().order_by('-deadline')

    @action(detail=True, methods=['get'], url_path='my-status')
    def my_status(self, request, pk=None):
        """
        Get the latest submission status and grade of the current student for a particular assignment.
        This interface retrieves the record of the student's last Submission,
        And query the published AI evaluation information.
        :param request: DRF request object
        :param pk: Assessment ID
        :return: Response: A dictionary containing status (submitted/not submitted), score, feedback, number of submissions, etc.
        """
        assignment = self.get_object()
        submission = Submission.objects.filter(student=request.user, assignment=assignment).order_by(
            '-created_at').first()
        if not submission:
            return Response({"status": "unsubmitted", "message": "Unsubmitted"})
        evaluation = AIEvaluation.objects.filter(submission=submission, is_published=True).first()
        return Response({
            "status": submission.status,
            "final_score": float(evaluation.total_score) if evaluation else "To be released",
            "feedback": evaluation.feedback if evaluation else "In the scoring process",
            "submitted_at": submission.created_at,
            "attempt_count": Submission.objects.filter(student=request.user, assignment=assignment).count()
        })


class StudentCourseViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Student side course view set.
    A read-only interface (List/Retrieve) is provided to allow students to view information about courses they have joined.
    ReadOnlyModelViewSet is used to ensure that students cannot create or modify course data through this interface.
    Permission Restrictions: Access is restricted to logged-in users only
    """
    serializer_class = CourseSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """
        Gets a list of courses that the current student has taken.
        Filtering by using the reverse association of students (many-to-many fields) in the Course model,
        Ensure that the query set returned contains only the current logged-in student himself.
        :return: QuerySet: The set of courses that the current student belongs to.
        """
        return Course.objects.filter(students=self.request.user)


class StudentSubmissionViewSet(viewsets.ModelViewSet):
    """
    Student assignments are submitted with automated processing of view sets.
    This set of views implements highly hardened commit logic, including:
    1. Submission Limit: check the student's course selection status and the maximum number of submissions allowed.
    2. Type automatic recognition: the back-end independently determines the type of single file and Archive.
    3. Asynchronous pipeline orchestration: Integrate ProjectAnalyzer and AIScorer for preprocessing and dispatch Celery asynchronous tasks.
    Permission Restrictions: Access is restricted to logged-in users only.
    """
    serializer_class = SubmissionSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """
        Get the submission history of the current student.
        :return: Sorting by creation time in reverse order ensures that students see the most recent submission record first.
        """
        return Submission.objects.filter(student=self.request.user).order_by('-created_at')

    def create(self, request, *args, **kwargs):
        """
        The core logic that handles student work submission.
        This includes pre-validation, pre-preparation for score calculation, and pipeline triggering.
        :param request: DRF request object, data should contain 'assignment' (ID) and 'file' (file stream).
        :param args: Variable positional parameters
        :param kwargs: Variable keyword arguments
        :return:
            Response:
            201: The submission was successful, and the processing prompt is returned.
            400/403: Validation failure (number of times exceeded or no permission)
            500: The system handles the exception internally.
        """
        assignment_id = request.data.get('assignment')
        file_obj = request.data.get('file')

        try:
            assignment = Assignment.objects.get(id=assignment_id)
            student = request.user

            # 1. Permission and frequency verification
            if not assignment.course.students.filter(id=student.id).exists():
                return Response({"error": "You are not authorized to submit this assessment"}, status=403)

            existing_count = Submission.objects.filter(student=student, assignment=assignment).count()
            if existing_count >= assignment.max_attempts:
                return Response({"error": "The maximum number of submissions has been reached"}, status=400)

            # 2. The backend makes an independent judgment on the file type.
            is_zip = file_obj.name.lower().endswith('.zip')
            calculated_sub_type = 'archive' if is_zip else 'file'

            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)

            # 3. Keep records
            submission = serializer.save(
                student=student,
                attempt_number=existing_count + 1,
                sub_type=calculated_sub_type,
                status='pending'
            )

            # 4. Enter Pipeline orchestration
            self.run_agent_pipeline(submission)
            return Response({"message": "Submission successful. System processing in progress..."}, status=201)

        except Exception as e:
            print(f"❌ ViewSet Create Error: {str(e)}")
            return Response({"error": str(e)}, status=500)

    def run_agent_pipeline(self, submission):
        """
        Arrangement logic: Handling the decompression, analysis of submitted materials, and dispatching Celery tasks.
        This method acts as a "central control console", responsible for completing the short-duration preprocessing tasks (such as decompression and entry analysis) in the Web main thread,
        and then asynchronously dispatching the heavy correction tasks to the background Workers to ensure that user requests can receive immediate responses.
        :param submission: Instances of submitted records in the database.
        :return:
        """
        from .tasks import run_grading_task

        # 确保基础临时目录存在
        temp_base = os.path.join(settings.MEDIA_ROOT, 'temp')
        os.makedirs(temp_base, exist_ok=True)

        temp_workspace = os.path.join(temp_base, str(uuid.uuid4()))
        os.makedirs(temp_workspace, exist_ok=True)
        entry_point = None

        try:
            print(f"[Pipeline] Commencing processing of Submission: {submission.id}")

            if submission.sub_type == 'archive':
                # Check the physical path
                file_path = submission.file.path
                print(f"[Pipeline] Checking file path: {file_path}")
                if not os.path.exists(file_path):
                    raise FileNotFoundError(f"The file was not saved correctly to the disk: {file_path}")

                scorer = AIScorer()
                analyzer = ProjectAnalyzer(ai_client=scorer)

                print(f"[Pipeline] Decompressing to: {temp_workspace}")
                analyzer.unzip_project(file_path, temp_workspace)

                print(f"[Pipeline] Analyzing the project structure...")
                contexts = scorer.get_rag_contexts(submission)
                task_requirement = contexts.get('l3', "Determine the entry point of the main program.")
                entry_point = analyzer.get_entry_point(temp_workspace, task_context=task_requirement)

            # Dispatch asynchronous tasks
            print(f"[Pipeline] Dispatching asynchronous tasks to Celery... EntryPoint: {entry_point}")
            run_grading_task.delay(
                submission_id=submission.id,
                temp_workspace=temp_workspace,
                entry_point=entry_point
            )

            submission.status = 'running'
            submission.save()
            print(f"[Pipeline] Status update successful: Running")

        except Exception as e:
            print(f"[Pipeline ERROR] Submission {submission.id} failed:")
            traceback.print_exc()
            submission.status = 'failed'
            submission.save()
