# Generated by Django 6.0.3 on 2026-03-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_submission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentKnowledgeMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_evaluations", models.IntegerField(default=0)),
                ("avg_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("latest_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("trend", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "kp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.knowledgepoint",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentOverallProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_avg_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "learning_ability_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rank_in_all_students", models.IntegerField(null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
